### ISSUE TITLE
Updated syllabus: CSCI 150 - Discrete Structures

### ISSUE THREAD

**Issue by A278PlusPi** [Hunter-Open-Source-Club/syllabi#25]
Updated the CSCI 150 syllabus for Spring 2023 to reflect the changes of his grading policies

[cs150_schweitzer_syllabus_s23.pdf](https://github.com/Hunter-Open-Source-Club/HunterCS_CourseSyllabi/files/10453478/cs150_schweitzer_syllabus_s23.pdf)

**Comment by joshnatis** [comment]
Thank you so much! Finally merged this in and added you as a contributor in https://github.com/Hunter-Open-Source-Club/syllabi/commit/9bdb29790102690e276d2e8cf42cefee7e832046. I'm beyond late getting to this, sorry.

Do you have any other syllabi on hand you can share?
